name: Code coverage

on:
  push:
    branches:
      - code-coverage-test

jobs:
  # Code coverage
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v2
      # gradle wrapper validation against official sha
      - uses: gradle/wrapper-validation-action@v1
      # setup java
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: DB Docker container
        run: |
          cd docker_data
          docker-compose up -d
      # gradle cache
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      # set permission to gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # build and test
      - name: Build with Gradle
        run: ./gradlew clean build
      # generate jacoco
      - name: Genereate jacoco test report
        run: |
          ./gradlew jacocoTestReport
          echo "######"
          ls build/reports/jacoco/test/jacocoTestReport.xml
          echo "######"
          pwd
      # codacy coverage reporter
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: /home/runner/work/MemPOI/MemPOI/build/reports/jacoco/test/jacocoTestReport.xml
